### ISSUE TITLE
SaveStateDict calls itself recursively and fails on locked file

### ISSUE THREAD

**Issue by BalashovK** [shaltielshmid/TorchSharp.PyBridge#16]
safetensors.cs line 50
SaveStateDict calls itself which causes 2nd attempt to open same output file.
Perhaps, intention was to call method SaveStateDict from line 55 and pass the stream?

**Comment by shaltielshmid** [comment]
Great catch, Thanks! 
Fixing now, will be in the next release

**Comment by shaltielshmid** [comment]
Should be up in version 1.4.0 in the next few minutes.
