### ISSUE TITLE
Strong naming?

### ISSUE THREAD

**Issue by LittleLittleCloud** [shaltielshmid/TorchSharp.PyBridge#19]
Hi @shaltielshmid, would you please provide a strong-naming version of this package so we can use it in mlnet project? I am happy to contribute a PR to enable strong naming if you don't have time.

**Comment by shaltielshmid** [comment]
I believe the latest version of the package published on NuGet is strongly named. Can you check?

**Comment by LittleLittleCloud** [comment]
@shaltielshmid Confirmed that the latest version `1.4.1` has strong named
