### ISSUE TITLE
Provide strong-name package

### ISSUE THREAD

**Issue by LittleLittleCloud** [shaltielshmid/TorchSharp.PyBridge#7]
Hey friend, thanks for this awesome package.

The package seems not to be strong-named assembly though, is there any plan to enable that feature? Thanks!

Here's some information about [strong-name assembly](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named#what-makes-a-strong-named-assembly)

**Comment by shaltielshmid** [comment]
Sure, will add it to next week
